### ISSUE TITLE
(1.3.2) Favorites Bug - Cannot longpress to add/remove favorites without a poster

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#103]
The favorites issues have not been fully addressed in the 1.3.2 update:

- If a show/film has no poster, you can not hold to "Add to Favorites" or "Remove from Favorites", you need to instad go into the show/film and then tap-untap the heart icon

**Comment by kevincosmos** [comment]
@SpajicM could you provide some context on this - I know you did some digging on this but can't find what you said in Discord.

**Comment by SpajicM** [comment]
Reason why this happens is here https://github.com/ApolloTVofficial/kamino/blob/master/lib/pages/smart_search/search_results.dart#L134 - not every result (TV/movie) has a poster, so it throws null.

I don't know why are we even passing around image URL and storing URL title and year (https://github.com/ApolloTVofficial/kamino/blob/master/lib/ui/ui_constants.dart#L19)
Only thing that should be needed is type (to separate TV and movie tabs) and ID (to pull it from TMDB).

**Comment by edmundackah** [comment]
@SpajicM we store these information for offline viewing and also making an API call every time is wasteful. The null bug has been fixed and will be rolled out soon

**Comment by NBTX** [comment]
@edmundackah offline viewing is a bit useless because the app doesn't support downloading. Though I agree it's worth saving the favorites images to reduce API calls.
