### ISSUE TITLE
Low contrast font on release notes

### ISSUE THREAD

**Issue by Chaphasilor** [ApolloTVofficial/kamino#106]
ApolloTV now checks for updates automatically, which is great, but there're still some issues.

For examample, when a new update is found the release notes for it are automatically shown. I use the light theme, but the font color is still white in the dialog:    
![Release Notes with white theme](https://i.imgur.com/NHzzrFl.png)

My suggestion: Use the accent color as font color here, because the user can make sure it has high enough contrast now matter which theme.

If you come up with a better solution that's also fine by me of course!

**Comment by NBTX** [comment]
This is actually a bug. It's presumably just been hardcoded to use white, when it should actually use a color based on the theme's brightness.
This is a simple fix and the text color should match that of the title or 'See All' button on the homepage cards.

**Comment by SpajicM** [comment]
Fixed by #124
