### ISSUE TITLE
Source Searching Overhaul

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#107]
When searching for content, if no sources have been found then the pop-up appears as normal. Once dismissing the "no sources found" pop-up, the "searching for sources..." stays active and continues spinning, I think it would make more sense for it to automatically close, or have a button for "Close" and "Try Again"

**Comment by NBTX** [comment]
Instead of loading sources indefinitely, if there is a problem or no sources are found after x seconds, have it time out and start again.

Additionally, the searching for sources dialog should be made more verbose so the user knows if waiting will actually result in a source being loaded.

**Comment by NBTX** [comment]
"Can we have a more detailed progress report on sources search.
Let's say "10/35 sources scraped, 2 found"

That's more reassuring than silently counting down 30 seconds in hope it will find one."

**Comment by kevincosmos** [comment]
Closed issue #62 and adding comments here:

"Manual source selection should be an option, but I have some idea's how to improve autoselect too.

I think one of key reasons why people buy Netflix is fast loading even on slow connection, there's no resolution selection at all.

My suggestion is this:

When application is started, make a speed test of the user's connection in the background.

When movie or TV show is selected, take previously measured user's internet connection, server response speed, file size (Metadata idea mentioned by deathbysnoosnoo in discord) and calculate a "best choice" for 360p, 480p, 720p...

Pass on those to player, so it's possible to have a resoution picker similar to YouTube.

This could greatly improve UX compared to quitting what you are watching to select a different source."

"Followup on this - since we now have a bunch of metadata, it may be a good idea to look into MPEG-DASH. If I understood it correctly, we could take sources metadata, generate MPD file, and let DASH handle the scaling up and down depending on network connection:

https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP
https://developer.mozilla.org/en-US/docs/Web/Apps/Fundamentals/Audio_and_video_delivery/Setting_up_adaptive_streaming_media_sources

EDIT: I'm not sure if this is possible without video being in "segments", but we'd need some kind of "if you notice buffer can't catch up, switch to lower resolution source at the same timestamp" algorithm, so I'm looking around that.

@NBTX let me know what you think?"

**Comment by polishboi** [comment]
What do you think of creating a search queue while your searches are being done in the background? I don't know if you played Rocket League but the basic concept is that your match is being looked for while you can still be browsing around the game.

I think it's frustrating when you have to sit there and stare at the spinner while your search is being done.

Some ways to display this would be e
• create a notification for each search (that would be clumsy)
• create a notification that one or more searches are being done and display the whole queue in the sidebar ( swipe from the right from any screen to see queue)
• just the queue thing

It would be quite easy for people to randomly tap around and overload the servers so maybe create a max queue size.

You may argue no one actually would search for multiple different TV shows/movies at once and the only way this feature would be used is trolling/overloading the server, but sometimes I don't know what I'm going to watch myself and I'll pick the first thing that loads. 

Is this even possible?

**Comment by edmundackah** [comment]
@polishboi such a feature will cause unecessary load on the server. Imagine having to wait while someone else' second show that he/she may not watch is scraping.

**Comment by SpajicM** [comment]
Source searching has been redone, now showing sources as they appear.

@polishboi the *real* solution would be to optimize the waiting times as much as possible, and we hope to get closer to it by implementing a cache for search results. Your notification idea really seems clumsy. Yes, searches take a while, but not like you'd be able to play a game of Rocket League in between :D
