### ISSUE TITLE
Add "Continue Watching" / "Watch Next" Card to Launchpad

### ISSUE THREAD

**Issue by JLDevUsr** [ApolloTVofficial/kamino#109]
A category that uses a dependent (like trakt.tv) to display specific episodes from various series that are not recognized as "Watched". - Something like Morpheus TV had.

**Comment by kevincosmos** [comment]
Hi, Just to clarify, which of the following are you asking for:
- Watch the next episode of a series based on your previously watched shows (this is already planned I believe)
- A category of recommendations based on what you have in your "Watched" history in Trakt (I'm not sure if this is technically feasible unless Trakt already has the feature and it's API can be used)

**Comment by JLDevUsr** [comment]
To clarify I am suggesting - A category that shows you the next episode of all series based on watched shows. If I watched Season 2 Episode 3 of Psych and Season 3 Episode 2 of The Flash then my watchlist category would display Season 2 Episode 4 of Psych and Season 3 episode 3 of The Flash.

**Comment by JLDevUsr** [comment]
I mocked up an image of what this category could potentially look like (obviously it would maintain the same style of the current categories rather than looking different.)
The Icons would go directly into Searching for Sources.
![examp watch next](https://user-images.githubusercontent.com/47650360/52895690-9d80af80-3172-11e9-8486-1241be9e9e7c.png)

**Comment by SpajicM** [comment]
Good idea, bad naming maybe. As @kevincosmos said, it's somewhat unclear what "Watch Next" would imply.

As for similar shows and recommendations, TMDB has 2 APIs for this https://developers.themoviedb.org/3/tv/get-tv-recommendations and https://developers.themoviedb.org/3/tv/get-similar-tv-shows though I'm not sure this could be implemented without keeping user info on Apollo's server, which is one of core Apollo principles.

**Comment by kevincosmos** [comment]
I've renamed the issue to make it a bit more clear what the actual ask is.

Not being a developer myself, I think that the most logical way to implement a "Continue Watching" feature would be to use the history of what you've watched from Trakt and then suggest the next episode.

@SpajicM TerrariumTV does this by storing a local 'watched_eps" file on your devicea, which could be implemented in Apollo if Trakt isn't the best route to go down. Nothing needs to be stored on the server to facilitate this.

**Comment by kevincosmos** [comment]
I'm going to close this issue and merge it into #88 to cover "Previously Watched" and "Watch Next" implementation
