### ISSUE TITLE
[Request] - Cast Before Playing An Epsiode

### ISSUE THREAD

**Issue by JLDevUsr** [ApolloTVofficial/kamino#113]
Casting before an episode starts would help cut down on the steps involved to watch multiple shows on a casting device.

**Comment by SpajicM** [comment]
Agreed, this was discussed in the beginning of Chromecast implementation and was decided to go with casting from player to simplify implementation (that's already quite complicated with lack of support for Flutter). May be reworked somewhere down the road.

**Comment by kevincosmos** [comment]
Closing this and tieing into #14
