### ISSUE TITLE
Add toggle to include anime sources

### ISSUE THREAD

**Issue by SpajicM** [ApolloTVofficial/kamino#118]
Since some users have asked to have Anime movies/shows separated. we should have a setting that includes or excludes those sources, and if enabled sends a type="anime" parameter to Claws.

Additionally, the toggle may be able communicate with TMDB to add/remove Anime results accordingly although I didn't investigate if this is possible.

After this is resolved, a workaround for Anime (https://github.com/ApolloTVofficial/Claws/commit/857bac9c91edc2f7c8062dbcd51b297c88c186ed) in Claws can be reverted.

**Comment by kevincosmos** [comment]
Just throwing this out there, it may not be applicable - currently TMDb has no "Anime" tag, so how would we identify what is and what is not an anime?

**Comment by SpajicM** [comment]
Can youu check a few of your favorites and see if they've an anime keyword. If it's consistent enough, we could use that 

[screenshot_20190219-222542_brave](https://user-images.githubusercontent.com/21988220/53160797-f3b57e80-35c8-11e9-9a09-f1505d10ea6f.jpg)

**Comment by kevincosmos** [comment]
I'm not a massive anime fan but I'll run through some of the top 100 list I made and see if it's consistent - will post back with results

**Comment by kevincosmos** [comment]
I picked 12 random shows and 4 of them did not have the anime tag.

I think a more consistent way to do this would be to use the following criteria for TV shows (this may have a bigger impact on films for popular things such as Spirited Away, so need to consider this):

- Original Language: Japanese AND
- Category: Animation OR - keyword: animation OR keyword:anime

**Comment by SpajicM** [comment]
The primary scope of this issue is filtering sources in/out as needed, altrough filtering search results along with it accordingly would be very welcome, or even expected from such toggle setting.
So yeah, I don't know. investigate more, and if you can confirm a reliable criteria for TMDB search, comment here.

**Comment by kevincosmos** [comment]
I've gone through a few shows and there is no set identifier to say "this is an anime"

The only way we can rule out MOST anime is to use the above criteria, but it won't work 100%
Alternatively, use an API like MAL/Kitsu as BlackKnit suggested and then filter out any results if it exists in those databases.

**Comment by kevincosmos** [comment]
Tieing this in to #108

**Comment by SpajicM** [comment]
Such cross checking is quite a big dev work. Once app overall gets more stable/usable day to day, we should do it probably.
For now, I'd say do it using TMDB whenever @NBTX comes around implementing the toggle. If a few anime's sneak in even when Anime is disabled, I don't think it's a big deal.

**Comment by kevincosmos** [comment]
Taken from 108 to keep conversation in one place:


![image](https://user-images.githubusercontent.com/30179692/53477979-c015a100-3a6d-11e9-8863-d7c920b68a5a.png)

**Comment by NBTX** [comment]
I'm going to close this in favor of #272 for tracking all progress with Anime as the state of Anime in ApolloTV goes pretty far beyond lack of a toggle.
