### ISSUE TITLE
Send year to Claws as a separate parameter

### ISSUE THREAD

**Issue by SpajicM** [ApolloTVofficial/kamino#119]
Currently, we append (year) to the title parameter, but including year seems to break some providers (eg. 123Movies)

Suggested fix is to send year to Claws as a separate parameter, and then have provider append it to search query if needed.

**Comment by kevincosmos** [comment]
Is this something you're going to create a PR for or do you need dev input first?

**Comment by SpajicM** [comment]
Hmmm... okay, I'll do it and make a PR, hopefully later today.

**Comment by SpajicM** [comment]
Fixed in #123
