### ISSUE TITLE
Implement End-User Friendly Error Messages (Can't reach TMDb etc)

### ISSUE THREAD

**Issue by omprasad2001** [ApolloTVofficial/kamino#122]
![screenshot_2019-02-21-18-44-06-28](https://user-images.githubusercontent.com/41458440/53171610-444ccc00-3609-11e9-8860-3e55f7e7a8f9.png)

**Comment by kevincosmos** [comment]
Isolated incident. Closing issue as resolved confirmed by OP

**Comment by NBTX** [comment]
We have now cleaned up all error messages.

![image](https://user-images.githubusercontent.com/43181178/55692984-6ecdcb00-59a4-11e9-9ad9-ca59b2ab0a83.png)
