### ISSUE TITLE
Implement a new subtitle source

### ISSUE THREAD

**Issue by guilhermepaesa** [ApolloTVofficial/kamino#127]
Legendas.tv is a very good source of Spanish and Portuguese subtitles. I wanted to know if you could add on the subtitle feature. I think it has an API here on GitHub. I don't know how it works.

Thanks.

**Comment by SpajicM** [comment]
While this won't be added in the official version of the app, you are very welcome to create your own fork and create a version of ApolloTV that would be tweaked to your local community! It's one of the key reasons Apollo was open-sourced :)

**Comment by FlyPigsFly** [comment]
There's also https://github.com/Kamikadze4GAME/cloudflare-bypasser

**Comment by polishboi** [comment]
@SpajicM would such a change be open for a merge? For example I was wondering about (one day) making a Polish streaming links provider, but then it would have to be marked somehow that the video contains either PL dubbing or hardcoded subtitles.

If international providers were to be supported, some settings would have to be added to let the user decide which languages they would like to search and display flags or language tags with some metadata about subtitles vs dubbing.

Or is this something that's never going to be considered, and multiple forks for each language would be needed?

I think the idea of anyone being able to create their own version of ApolloTV is great and all, but in practice having to switch to different apps for different languages ( maybe someone wants to find a Polish movie, maybe they watch English movies with subtitles, but they like to watch animated movies in their native 👅 dubbing ) would be pretty cumbersome.

**Comment by SpajicM** [comment]
I'm not the one who makes the call on this, but anyway here's my take on this:

Adding sources and filtering them would definitely be an option (have local-centered providers disabled by default probably), but as for subtitles, I think it's not a good idea to have a bunch of different APIs for each subtitle site that people want to be added. OpenSubtitles is a way to go, and maybe a few other popular (global) sub providers later.

You'll for sure have the option to load SRT file like you would normally do for any video played.

**Comment by NBTX** [comment]
I'm going to close this. Whilst we do plan to implement OpenSubtitles we do not at this time intend to implement multiple subtitles providers.
