### ISSUE TITLE
Push Notifications (Favourite Show has a new episode etc)

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#129]
Requested by BradB:

Push Notifications so that ApolloTV tells you when a new episode of your favourite shows has aired.

My own notes:
- If implemented, IMO this should be turned off by default.
- I don't think TMDb has API calls for checking what time of day something has aired, so maybe a simpler implementation would be to send a push notification the day after a show has aired to inform the user they have a new episode to watch (it will check if they have watched it first before sending the notification)

**Comment by BradB111** [comment]
Maybe an option to notify at a set time on the day of release also? "<Your favourited show> has an episode airing later today" (to be pushed at 9am local time / user configurable time)

**Comment by NBTX** [comment]
Or we could even wait until a valid link can be found by the server and then send the notification

**Comment by BradB111** [comment]
@NBTX I did briefly think about that but thought it would cause unnecessary load on the server just to check if something is there? How would this work?

**Comment by polishboi** [comment]
@NBTX if notifications were done messaging the episode has aired, imo this is the only way this would make sense

Imagine getting a notification from a streaming app about the episode airing but not being able to play it there anyway.

**Comment by BradB111** [comment]
@polishboi Then the user would simply turn off that notification in the settings that gives you notice prior to the episode is airing. 
I'd love to be notified ahead of time that a new season / episode is due to be released. As half the time I don't even realise my favourite shows are airing episodes.

**Comment by polishboi** [comment]
@BradB111 understandable, have a nice day

**Comment by NBTX** [comment]
@polishboi we would try to use something along the lines of Google Cloud Message (I think that's now Firebase Cloud Message)

"Android keeps one active connection to Google's servers, but it doesn't use much power or data, because no traffic is sent along it until something sends a GCM message to an app on your phone. There's only one connection on the phone, used by all apps: installing a new app that uses GCM doesn't add any extra load."

**Comment by SpajicM** [comment]
Thinking about this more now...
@polishboi you're pretty much correct. Two main options are doing it fully manually, having Android service in the background periodically checking for messages on our server and creating a notification out of that. Or use FCM (or other services that use FCM behind the scenes anyway).

I'm fairly familiar with FCM, it's a nice solution, however it would still require us to build a system that would, as mentioned above, do a scrape periodically and send out a notification.

Also a thing do note is Google might terminate the account if they figure out what kind of an app is using the service.

In theory, this would be steps to implementing this:

1) You select for example 5 shows you're following and want to be notified for.
2) App sends selected shows and your FCM device token and stores it into our database
3) Our server checks date for next episode of the selected show
(_one might think this can be done on client - it can't. You'd have to open the app to do so. We'd need to integrate TMDB on the server)_
4) When the date of supposed episode comes, our server should call the Claws server to scrape, if results are found, it gets the associated device tokens and sends a notification.

This even might be reasonable for TV shows - but real problem would be movies, if someone wants a notification on when movie is released, it probably won't appear on the sites right away like TV shows are, and even then you would get a CAMRIP quality first. And we can't afford to scrape every day for the next month checking if HD is out.

I'm closing this - while this indeed is a cool feature, especially for TV shows, you can call it almost a separate project, and for sure won't be done in forseeable future.
