### ISSUE TITLE
OTA Updates [original issue moved to CPlayer]

### ISSUE THREAD

**Issue by roc2814b** [ApolloTVofficial/kamino#13]
I Saw someone else got the red screen when trying to play, but I also got it when I hit my phone's back button after placing a movie

**Comment by NBTX** [comment]
Make sure you're running the latest version.
If it doesn't show 'Searching for Sources' you're using an outdated one and need to update it.

**Comment by kevincosmos** [comment]
There are plans in place to introduce OTA updating, but it hasn't been implemented yet.

**Comment by kevincosmos** [comment]
Closing as OTA has been implemented.
