### ISSUE TITLE
[Request] - Favorites Shortcut button customization

### ISSUE THREAD

**Issue by JLDevUsr** [ApolloTVofficial/kamino#133]
Obviously the title is not that great for the following suggestion. If there was an option that allowed you to change the "Favorites" button in the top right to link to different cards it might make things easier for people who like to constantly check shows in cinema. I am mainly suggesting this with the personal intent to have a quick access button to view "Continue Watching" / "Watch Next" shows from issue #88

**Comment by kevincosmos** [comment]
This seems like a lot of work when you could simply have "Continue Watching / Watch Next" as a default card on the launchpad?

**Comment by NBTX** [comment]
We're adding continue watching to the homepage by default now, and as OP has not replied, I'm closing this in favor of the new feature.
