### ISSUE TITLE
[Request] - Bottom search bar

### ISSUE THREAD

**Issue by JLDevUsr** [ApolloTVofficial/kamino#138]
Option to move the search bar to the bottom of the screen. Would work with #137

**Comment by SpajicM** [comment]
I'm not in favour of so many options. We should just consider best option and placement for searchbar.

While having customization might be cool, it adds alot of code and complexity. On the other hand, project is opensource and anyone can do a tweaked version however they like it. We can't please everyone (without having a mess of customizable code)
