### ISSUE TITLE
i18n pluralization support

### ISSUE THREAD

**Issue by polishboi** [ApolloTVofficial/kamino#140]
My PR #139 is still open and I have found this problem. The number of episodes should be different for three cases: {1}, <2 - 4> <5 - ∞) , yet I'm provided with just: {1}, <2 - ∞).

This is the current behaviour:
https://github.com/ApolloTVofficial/kamino/blob/522962bcb6f5b868e34137da162e83aa255bfe37/res/values/strings_en.arb#L55-L56
However, in Polish what I'd need to be gramatically accurate is something like this:
```json
 "one_episode": "1 odcinek", 
 "2-4_episodes": "$n odcinki", 
 ">4_episodes": "$n odcinków", 
```
Same goes for the `"n_ratings"` key:

https://github.com/ApolloTVofficial/kamino/blob/522962bcb6f5b868e34137da162e83aa255bfe37/res/values/strings_en.arb#L49

=>

```json
 "1_rating": "1 ocena", 
 "2-4_ratings": "$n oceny", 
 ">4_ratings": "$n ocen", 
```

I don't know if you'd like to do it the way I'm showing. Maybe in different languages it's even more complicated and requires different cases than just these three. If the translator could specify the numbers like I did there I think it would be the best.

Here's how that's handled in vue-i18n: https://kazupon.github.io/vue-i18n/guide/pluralization.html

I think there's no need to reinvent the wheel. I'm not familiar with the codebase, its dependencies and frameworks used but maybe there's an i18n library for Dart/Flutter implemented.

**Comment by SpajicM** [comment]
This is needed from proper Croatian grammar as well. got a pretty complex conjunction and inflection.

**Comment by NBTX** [comment]
We use the Flutter i18n plugin for this, here's what the documentation says about pluralisation:

"_Plural translations can be provided for several quantities: 0, 1, 2, "few", "many", "other". The variations are identified by a resource ID suffix which must be one of "Zero", "One", "Two", "Few", "Many", "Other". The "Other" variation is used when none of the other quantities apply._"

The problem I see is that the plugin doesn't have enough flexibility to implement this automatically - though I did expect that we would encounter this problem.

Here's the plugin: https://plugins.jetbrains.com/plugin/10128-flutter-i18n

**Comment by kevincosmos** [comment]
My take on this:

We should stick to the plugin's guidelines as much as possible. It will be too difficult to cater for each language's specific grammatical syntax properly. so If there's something @polishboi and @SpajicM can do to make it "workable" language then I'd go with that approach. We should cater for as many languages as possible at a basic level (i.e. sticking to the plugin's guidelines), but for true localization forks may be needed to reinvent the wheel for them.

**Comment by polishboi** [comment]
I don't quite understand the "Few" and "Many" options, but if they work as I said, i.e. few was <2-4>, many was >=5, then I'd be happy.

**Comment by kevincosmos** [comment]
I think few being 2-4 and many being 5 and above is the best way to go

**Comment by SpajicM** [comment]
Agreed on few 2-4, many 5 or more

Would work for Croatian

1 epizoda
2 epizode
3 epizode
4 epizode
5 epizoda

**Comment by NBTX** [comment]
Okay I've updated the documentation to include the convention. All plural quantities will begin with `plural_` so that it's clear that it needs to be implemented. Then they key will be made camelCase (so that it can be used with the Flutter i18n plugin.)

e.g. `one_episode` would become `plural_episodesOne`
`two_episodes` would become `plural_episodesTwo`

I will update this issue when the English language files have been updated so this change can be reflected.

You can see more information in the documentation: https://learn.apollotv.xyz/portal/enthusiasts/translate-apollotv#faq

**Comment by polishboi** [comment]
Isn't 2 included twice? In "Two" and "Few"?

**Comment by NBTX** [comment]
Resolved.
