### ISSUE TITLE
Pass IMDB ID & TMDB ID To Claws

### ISSUE THREAD

**Issue by Teekzilla** [ApolloTVofficial/kamino#158]
**Overview**
As the title says, it would be nice to send the IMDB ID of a movie or TV show in the query to Claws. This information will be used in future providers (i.e. DibaMoviez) and might be useful for current providers as well.

**Implementation**
For movies, if we are calling the `/movie/{movie_id}` endpoint for information, the IMDB ID is already there as `imdb_id`.
For TV shows it will be necessary to utilize the `append_to_response` query parameter with `external_ids`. For example the call could look like: http://api.themoviedb.org/3/tv/500?api_key=XXXXX&append_to_response=external_ids. Utilizing that query parameter will allow us to avoid making a separate call that would count against the rate limit.

**Relavent API Documentation**
- [Movies Details](https://developers.themoviedb.org/3/movies/get-movie-details)
- [Append To Response](https://developers.themoviedb.org/3/getting-started/append-to-response)
- [TV Show Details](https://developers.themoviedb.org/3/tv/get-tv-details)
- [TV Show External IDs](https://developers.themoviedb.org/3/tv/get-tv-external-ids)

**Comment by ddivad** [comment]
We should also use the same API call to add TMDB ID to the call to claws.

So we should send `imdbId: imdb_id`, `tmdbId: tmdb_id` to claws as these can then be used for some providers to help find content via the url method mentioned above.

**Comment by NBTX** [comment]
The client now sends `imdb_id` in the initial data payload.
