### ISSUE TITLE
Favorites button is unresponsive

### ISSUE THREAD

**Issue by deadpoetic45** [ApolloTVofficial/kamino#16]
I was able to re-create the issue with several movie and tv show titles, where clicking the favorites heart icon does nothing. I'm assuming this fills in once it selected. I think there should even be a confirmation of "favorited" text flashed briefly as soon as it's clicked too.

**Comment by SpajicM** [comment]
Known, not implemented yet.

**Comment by ddivad** [comment]
Yea, this isn't implemented in the beta yet, maybe this can be closed or changed to a feature-request / todo item @nbtx

**Comment by kevincosmos** [comment]
Closing this as it's not an issue, this is expected behaviour.

**Comment by NBTX** [comment]
This feature has now been implemented.
