### ISSUE TITLE
Error when playing content on Mobile Data (no Wi-Fi)

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#163]
**Describe the bug**
I get the following error when I press "Play Movie" when not connected to Wi-Fi

![](https://cdn.discordapp.com/attachments/533004633195413524/566403448539578368/Screenshot_20190413-002458.png)

**Expected behavior:**
Content plays

**Actual behavior:**
Above error

**NOTES**
 - Device: Pixel 2 XL
- Network: EE
- Works when using VPN

**Comment by NBTX** [comment]
The issue appears to be with the cell provider blocking access to the NTP servers.
Attempted fix: https://github.com/ApolloTVofficial/Claws/pull/87
