### ISSUE TITLE
Hide unreleased content (perhaps add option in Settings to show it)

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#167]
When sorting films/shows/results by Release Date > Descending, the first results are often things which are not out for years - which we will not have links for. This can be a frustrating experience for the user.

The proposal is to hide anything which has an initial release more than 1/2 months ahead of the current date - this number is flexible and has been chosen due to the fact that films can often leak a month or so ahead of time, so we need to cater for that.

**Comment by NBTX** [comment]
Proposal: Hide unreleased content (perhaps add option in Settings to show it)
We could maybe also add a slider that allows the user to choose how far into the future unreleased content should be allowed.

**Comment by NBTX** [comment]
This has now been implemented.
