### ISSUE TITLE
Default Sorting on Source Selection

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#169]
I believe that the default sorting on Source Selection should be Quality > Descending. In my view, a vast majority of users are going to pick a 1080p link with higher ping than a 480p link with less ping.

Additionally, if the user has Real Debrid then any RD links should appear on top of the list, again sorted by Quality > Descending. Users of RD are highly unlikely to use non-RD links if an RD link is avaialble to them, so they should have these options presented first.

**Comment by Chaphasilor** [comment]
Makes sense, although I'd recommend to also consider file size when sorting by quality. Larger files are far more likely to have better quality, so if two links are flagged as 1080p, but one is 600MB and the other is 1.5GB, the 1.5GB one should rank higher.  
This is especially useful when using the autoplay feature.

**Comment by kevincosmos** [comment]
> Makes sense, although I'd recommend to also consider file size when sorting by quality. Larger files are far more likely to have better quality, so if two links are flagged as 1080p, but one is 600MB and the other is 1.5GB, the 1.5GB one should rank higher.
> This is especially useful when using the autoplay feature.

We don't currently support multiple layers of sorting, so would have to go from the base level of quality.
Just to point out that whilst your statement stands true for the most part, this isn't always the case when HEVC (x265) is involved, and it is growing more popular as a standard.

The autoplay is very experimental at this stage and will need more work going forward.

P.S. you seem to have a lot of valid input, you should consider joining out Discord server if you haven't already: https://discord.gg/fkkmqQj

**Comment by Chaphasilor** [comment]
I edited my comment to better adjust to the things to mentioned :)
Can Claws detect whether an advanced codec is used or not?

As for discord, I'm a long time member of the server but there're a bit too many messages to plow through, so I focus on the actual issues here, where the devs have a better chance of seeing it.

**Comment by kevincosmos** [comment]
I guess we are now going back to issue #102 slightly
The only way we could currently get metadata like codec would be to regex the title, which works in most cases for RD links but not standard links.

![](https://i.imgur.com/j0EA1rN.png)

**Comment by Chaphasilor** [comment]
Yes this would also be a solution. Although I wasn't explicitly looking for an option to manually select multiple criteria but instead rank the sources base on a weighting system

**Comment by kevincosmos** [comment]
Yeah I appreciate that what you were suggesting is slightly different, the problem with that is that it would require a lot of our input and experimentation to get the balance just right, and assumes that the experience is the same for everyone. My suggestions puts the control in the users hands to choose what they do/don't want

**Comment by Chaphasilor** [comment]
The eternal struggle between customization and convenience, which offers better UX in this case?  
I think the community will decide this one way or another

**Comment by NBTX** [comment]
By default, we now sort by quality descending *and* we do a secondary sort by quality in the direction that the user has selected (i.e. ascending or descending), so I'm going to close this.
