### ISSUE TITLE
Search does not reset viewing position to top of list

### ISSUE THREAD

**Issue by kenmar3** [ApolloTVofficial/kamino#17]
After you run a query/search, it doesn't reset widget. You have to scroll back up to the top to see new result.

**Comment by kevincosmos** [comment]
Can you elaborate on this a bit more please? I don't fully understand the issue

**Comment by dali546** [comment]
Basically if I was to search Minions I get a list of minions movies. I scroll down and I'm half way down the list ...

Then I decide to search Venom. I click search, the tiles and images update but the position in the list stays the same... It does not go back to the top, nor does it give a reassuring loading spinner

**Comment by kevincosmos** [comment]
Thanks for clearing that up, I was able to reproduce the problem and I agree it doesn't seem logical from a user experience side. Can you edit the title of your post to something a bit more elaborate

"Search does not reset viewing position to top of list" or something similar.

Thanks.

**Comment by ddivad** [comment]
Fom #20:  Instead of new search results overwriting the old ones as they're being loaded, old search results should be removed and replace with a loading spinner while new ones start appearing. 

Collating this into this issue to keep it in the same thread, as it sounds like the same root cause.

**Comment by edmundackah** [comment]
Will investigate this issue further

**Comment by edmundackah** [comment]
Fixed this issue
