### ISSUE TITLE
Search Results - Favourited items have all text in gold

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#175]
When the user searches for a show, if one of the results is in their favourite then all of the text for that item on search results appears in gold - this looks off.

My proposal would be to either have just the title in gold, or to have a visual indicator of favourite (i.e. red heart in top right of poster

See below example of issue:

![image](https://user-images.githubusercontent.com/30179692/56274955-b0264f00-60f7-11e9-87e1-d8f3697c5d49.png)

**Comment by NBTX** [comment]
This has been changed in the latest builds.
