### ISSUE TITLE
"Flutter.Plugin.Common" Does Not Exist when trying to build Kamino

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#182]
Two users have verified the above error when trying to build Kamino:

![](https://cdn.discordapp.com/attachments/523867470063468544/568374823860830208/unknown.png)

Steps to reproduce:
1. Download Zip of latest Kamino and cplayer repos
2. Unzip both
3. Put cplayer into the cplayer folder under the Kamino directory
4. Open in IDE
5. Run flutter packages get in both the kamino and cplayer directories.
6. Run flutter clean in both kamino and cplayer directories.
7. Try flutter run and then you will see the errors.

flutter run --verbose results: https://hastebin.com/cayenexuyu.coffeescript

**Comment by NBTX** [comment]
Is this isolated to visual studio?

**Comment by SpajicM** [comment]
@NBTX  No it's not. Confirmed across 2 PCs with Android Studio.

**Comment by NBTX** [comment]
Nevermind, this is intentional. I forgot about this.
I'm updating the documentation to reflect the additional step.
