### ISSUE TITLE
Client-Sided Scraper

### ISSUE THREAD

**Issue by DreighUpstairs** [ApolloTVofficial/kamino#197]
It would be nice to have something other than the server sided scrapper to rely on in case maintenance is needed.

**Comment by kevincosmos** [comment]
There are plans to support client-side scraping in the future, but it hasn't been started yet.

**Comment by NBTX** [comment]
I will close this issue for now. We don't have an ideal way of implementing client-sided scraping at the moment and it's really not something we'll be looking at in the near future.

With regard to maintenance or uptime; It's easy enough for anyone to host their own server, which is exactly what I'd recommend doing if need be - not to mention that at the moment TMDB is offline more frequently than our server.
