### ISSUE TITLE
TV show watch status

### ISSUE THREAD

**Issue by adamgiesinger** [ApolloTVofficial/kamino#198]
**What feature would you like added to the app?**
If I have started watching and then close ApolloTV and open it again later and navigate to the episode I watched before it'd be great if it would automatically skip to the location I was when I closed ApolloTV.

**Comment by DreighUpstairs** [comment]
See #88

**Comment by adamgiesinger** [comment]
Shouldn't be a duplicate anymore now.

**Comment by DreighUpstairs** [comment]
A good example of this is the way Morpheus tv works. Using trakt data it will take the last show you were part way through watching and resume where you left off. Id like to add that it would be helpful for this feature if the "Continue Watching" information contained not only the shows name but also the season and episode number. It would be nice if clicking on the icon would also take you to that specific episode.

**Comment by kevincosmos** [comment]
"Continue watching from X minutes" is planned :) Closing this as it's kind of a duplicate.
