### ISSUE TITLE
Sort favorites by title

### ISSUE THREAD

**Issue by DreighUpstairs** [ApolloTVofficial/kamino#206]
I'm not sure how favorites sort right now; however, It is for sure not by title.

**Comment by kevincosmos** [comment]
The current sort is by first/last watched. There are plans to sort by Title already in place :)

**Comment by DreighUpstairs** [comment]
Are there any plans to sort by something along the lines of "Percentage watched" (like if I watched "The Flash" and have three episodes left unwatched vs "The Arrow" with only two episodes watched) if that makes any sense?

**Comment by Chaphasilor** [comment]
> Are there any plans to sort by something along the lines of "Percentage watched" (like if I watched "The Flash" and have three episodes left unwatched vs "The Arrow" with only two episodes watched) if that makes any sense?

Thing is, which would rank higher? If you watched a show for some seasons but got tired of it, and then start a new show you'd want the new show to rank higher.  
But if you tried out a show and didn't like it after a few episodes, you'd want your other shows to rank higher.  
Therefore I don't think this is practical honestly.

**Comment by kevincosmos** [comment]
Sorting by "Continue Watching" is a very delicate balancing act - we can easily show you what you've recently watched, but not so easily sort that in a context that works for everyone.

**Comment by NBTX** [comment]
This has now been implemented.
