### ISSUE TITLE
A new movie category based off a agoodmovietowatch.

### ISSUE THREAD

**Issue by akashrajum7** [ApolloTVofficial/kamino#209]
**What feature would you like added to the app?**
I really love the suggestions made by https://agoodmovietowatch.com, is there a possibility of adding this as a category?
I don't know if they provide an API, if they don't, maybe you could talk to them and see if they'll provide you one, in return they'll get recognition.

Thanks.

**Comment by SpajicM** [comment]
From what I can see, they don't have the API, and we are good with TMDB so far. The lists are handpicked by our staff :) @kevincosmos
