### ISSUE TITLE
Downloading movies

### ISSUE THREAD

**Issue by CyberLykan** [ApolloTVofficial/kamino#212]
**What feature would you like added to the app?**
The ability to download movies.

**Describe the solution you'd like (optional):**
A long press would open up a menu with the option to download the movie and, as already implemented, copy the URL.

It would also be nice to have a section in the app to track the progress of those downloads, and play them once completed.

**Additional context**
This suggestion is made so that users would not have to experience any buffering issues.

Downloads section would contain two pages. "In Progress" and "Completed"

**Comment by SpajicM** [comment]
It's been discussed and the decision is not to add downloading for legal reasons.

**Comment by Teekzilla** [comment]
I believe a stance was already taken on this if I'm not mistaken. The stance being that ApolloTV will not support downloading directly. You can however always long press to copy the link you see and open it in a third-party downloading application.
