### ISSUE TITLE
Favorite Color Search

### ISSUE THREAD

**Issue by include-mark** [ApolloTVofficial/kamino#213]
**Describe the bug**
Favorite color doesn't change search bar "search" text color. 

**Expected behavior:**
"Search" text in search bar should match favorite color. 

**Actual behavior:**
"Search" remains purple. 

**Steps to Reproduce:**
A list of steps that will reproduce the error.
1. Go to "search bar" after changing favorite color other than purple
2. See error

**Screenshots:**
https://photos.app.goo.gl/NYgFzAqm54UNGXs88

**Device Information:**
 - Device: Pixel 2 XL
 - OS: Android 9
 - CPU Architecture: ARMv8

**Comment by kevincosmos** [comment]
I believe this is actually an issue with the Flutter framework and not something Apollo can control at this point

**Comment by kevincosmos** [comment]
Closing issue. @NBTX feel free to reopen if I'm wrong.

**Comment by NBTX** [comment]
Don't know why I re-opened this, I could've just commented.
Either way - issue is now fixed (I found a workaround within the app but I am working on resolving this Flutter-side).

PR on Flutter (not mine) is https://github.com/flutter/flutter/pull/30388

**Comment by NBTX** [comment]
This issue has been resolved in the new (v1.4.8+) search UI.
