### ISSUE TITLE
"Invalid Date Format" error - TMDb Unknown Year?

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#216]
I believe this happens when a show/film hsa a release date of "Unknown" (see "Little Rascals" or "Our Gang Greatest Hits")

![2](https://user-images.githubusercontent.com/30179692/56962865-6bff6980-6b4f-11e9-9e0b-f4752d257ca1.png)

**Comment by NBTX** [comment]
Indeed it doesn't have a year.d

**Comment by kevincosmos** [comment]
Closing as this should now be resolved
