### ISSUE TITLE
OTA Updates Do Not Install

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#218]
When on v1.4.0, the user is prompted to install the update for v1.4.1. The app downloads the file but then doesn't present them with the standard android "Install Application" screen, nothing happens.

**Comment by corkiejp** [comment]
Solution Maybe?

Make sure the app has permission to download and also to install from unknown sources.

**Comment by kevincosmos** [comment]
> Solution Maybe?
> 
> Make sure the app has permission to download and also to install from unknown sources.

I think it's related to some of the updates we've made to the app, rather than due to a lack of permissions.

**Comment by NBTX** [comment]
@kevincosmos One of the changes made to the OTA update code was to the permissions API. Could you check that the app has the permission in settings and if not, enable it and try again?

Here's a link to the v1.4.0 build: https://houston.apollotv.xyz/ota/5cc64516f6421d58331faf6e

**Comment by kevincosmos** [comment]
@NBTX I have uninstalled the most recent version, restarted, reinstalled using the above link and granted file permissions (verified in Settings). I got the belomessage on first launch after allowing permissions. I also tried to manually pull the update twice, it downloads the file and then nothing happens (as described in original post)

![Screenshot_20190501-081104](https://user-images.githubusercontent.com/30179692/57008565-f7790900-6be8-11e9-95b0-75d5c584d223.png)

**Comment by NBTX** [comment]
Fixed in v1.4.5
