### ISSUE TITLE
Remove Ping from Source Select Screen

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#219]
As discussed, Ping is a very misleading thing to have on source select screen and it should not be used.

Ping is not an indicator of speed. Many free providers limit download speeds, so selecting the lowest ping does not mean you get the fastest speeds (see FardaDL as an example, it has low pin but they highly cap download/stream speeds).

**Comment by Chaphasilor** [comment]
Could faster providers be highlighted in some way, like they used to be in TTV? For example by having a different background color or graying out slower links.  
Maybe even have Claws do a speed test for various providers once a day/week...

**Comment by kevincosmos** [comment]
> Could faster providers be highlighted in some way, like they used to be in TTV? For example by having a different background color or graying out slower links.
> Maybe even have Claws do a speed test for various providers once a day/week...

This certainly seems like a good idea on surface level, but isn't without its faults - not everybody will have the same experience with links.
We certainly know which providers are slower (FardaDL) because they actively limit the speeds, but for things like Openload and Streamango it's not as simple to pre-determine everyone's experience as it varies wildly on a lot of factors.

Obviously if you have RD we have those links seperated and highlighted in their own sub-section at the top of the page, so people who use RD will most likely always go for those.

**Comment by Chaphasilor** [comment]
> This certainly seems like a good idea on surface level, but isn't without its faults

It doesn't have to be exact to work, but if providers which are generally faster (slower) could be highlighted (grayed out), you could locate 'favorable' links way faster. If they aren't actually faster for you doesn't really matter as they most likely won't be slower either.

**Comment by kevincosmos** [comment]
I think we are kind of doubling the conversation being has in issue 169?

**Comment by Chaphasilor** [comment]
> I think we are kind of doubling the conversation being had in issue 169? slightly different but both related to each other sort of

Maybe, but I don't think this highlighting should actually affect sorting.

**Comment by NBTX** [comment]
Done in v1.4.5
