### ISSUE TITLE
Suggestion - Movies Overlay Blank Space

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#22]
Too much blank space on Movie overview page, perhaps a section under "Similar Movies" showing the actors on the movie you're currently viewing and you can click the actor to find other work by them.

EDIT: Expanding upon this following @SpajicM's comment - we could have settings for the overview pages that allow the user to turn on/turn off the sections such as "Similar Movies" "Starring" etc

**Comment by SpajicM** [comment]
This seems like a step from clean UI to cluttered. Also it's more download/loading for the user, especially on a slower connection... I'd go for this only if TMDB has a low resolution image of actors.

**Comment by kevincosmos** [comment]
Expanding upon this following @SpajicM's comment - we could have settings for the overview pages that allow the user to turn on/turn off the sections such as "Similar Movies" "Starring" etc

**Comment by NBTX** [comment]
That's a valid point, @SpajicM, but my intention was always to add actors to the page.
I am conscientious about ensuring we don't bloat the app and make unnecessary requests but for a lot of people actors is a helpful feature.

I'll keep this open as I do plan to further improve the design of the overview page.

**Comment by SpajicM** [comment]
Can be closed, Cast & Crew is there now :)

**Comment by edmundackah** [comment]
@SpajicM which commit?

**Comment by SpajicM** [comment]
@edmundackah 

![Screenshot_20190318-184445](https://user-images.githubusercontent.com/21988220/54555170-76f2a600-49b6-11e9-8933-16e85961dc31.png)

@NBTX push pending

**Comment by NBTX** [comment]
This has been pushed.
