### ISSUE TITLE
Long TV Show/Movie titles push number of sources off screen in source selection

### ISSUE THREAD

**Issue by Chaphasilor** [ApolloTVofficial/kamino#220]
**Describe the bug**
_Please write a brief description of the bug you're experiencing to help prevent duplicate reports._

Long TV Show/Movie titles push number of sources off screen in source selection

**Expected behavior:**
_A brief description of what you expected to happen._

The long title gets truncated after 10-15 characters (e.g. Spider Man:  Int...) and the number of found sources is still visible.

**Actual behavior:**
_A brief description of what actually happened._

If the title is too long though (e.g. Spider Man: Into the Spider-Verse), the title isn't truncated and continues out of the screen boundaries, pushing 

the number of found sources even farther to the right, rendering it not visible.

**Steps to Reproduce:**
_A list of steps that will reproduce the error._  
1. Search for sources on any movie or tv show with a title longer than ~20 characters
2. Look at the header bar
3. The number of found sources is not visible

**Screenshots:**
_If applicable, add screenshots to help explain your problem._

Expected (only with short titles currently):
![Screenshot_20190430-161441](https://user-images.githubusercontent.com/18015147/56968646-d6baa000-6b63-11e9-87a4-0e617b867e81.jpg)  

Actual (with long titles):
![Screenshot_20190430-161544](https://user-images.githubusercontent.com/18015147/56968657-dae6bd80-6b63-11e9-9792-e36cf8c543df.jpg)

**Device Information:**
 - Device: OnePlus 5
 - OS: OxygenOS Open Beta 29 (Based on Android 9)
 - CPU Architecture: ARMv7 (Snapdragon 835)

**Comment by kevincosmos** [comment]
Thanks for reporting this

**Comment by NBTX** [comment]
I think I prefer truncating @kevincosmos but actually I may perhaps move the source found info onto a second line below the title.

**Comment by SpajicM** [comment]
I think 'subtitle' is the way to go

**Comment by NBTX** [comment]
Fixed in the latest build by moving to a second line below the title.
![image](https://user-images.githubusercontent.com/43181178/58641932-1d7eef80-82f4-11e9-887a-c179982f08fb.png)
