### ISSUE TITLE
Favorite duplication

### ISSUE THREAD

**Issue by exalented** [ApolloTVofficial/kamino#229]
**Issue:** It is possible to (seemingly) infinity duplicate a favorited show or movie.

**Explanation:** When one clicks on the favorite it gives the option to favorite it again. Then on a refresh a new dupe pops up. This prevents one from easily fixing their favorites if they've accidentally encountered this bug.

**Steps to Reproduce:** Browse for a show/movie and spam the favorite/unfavorite ❤️ icon a bunch and end with it unfavorited. Then go back out and into your favorites section of the app. Swipe down to see a bunch of duplicates of that show/movie.

**Temp fix:** Fixed by either clicking on the bugged favorite and backing out of it or spamming (un)favorite button over and over again then backing out and refreshing..

**Code Proposal:** perhaps just disable the button until the app can confirm the favorite is saved?

**Device Information:**
 - Device: Sexynos Note 9 Oreo w/ Magisk | N960F/DS

**Image of issue:**
https://cdn.discordapp.com/attachments/548601190963740683/573323152755654656/SmartSelect_20190501-184031.jpg

**Comment by kevincosmos** [comment]
Going to close this issue as it is not reproducable on latest build (v1.4.2 internal)
