### ISSUE TITLE
Suggestion - Identify Beta Build on Splash Screen

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#23]
have the build number on bottom left of the splash screen so that we can easily identify what version someone is using and they can include the build number when they are reporting issues.

**Comment by ddivad** [comment]
We can view the build in the settings for the app, but I don't think the build number has changed with the new releases (its still v1.0.0_build-100000). @NBTX is incrementing that each time there's a new build easy to implement? If so, at least the build number is there, but I like the idea of adding it to the Splash Screen as well.

**Comment by NBTX** [comment]
You mean automatically every time you hit build? If so, I haven't checked.
I'll add a flag for 'pre-release' mode and I'll look into adding it to the splash screen (though that's not handled by Flutter, it's handled by an Android layout XML file)

**Comment by ddivad** [comment]
@NBTX I get that the splash screen is done from xml, but there should be some file that has the version too, right? I see it in the `pubspec.yml` for example. 

So in that case you might be able to pull in the version from the file to the xml and display there. You could always set it up to dynamically insert the version into the xml file at build time too, but not sure how complex that would be using the Android builds, but I've done it like that for node applications too before.

**Comment by kevincosmos** [comment]
Closing my issue as the build number is easy to identify in the settings. Going to include this in #91
