### ISSUE TITLE
type '_Smi' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by DanielValahul** [ApolloTVofficial/kamino#238]
**Describe the bug**
This is an error that I recently encountered on the latest version of ApolloTV app (v. 104013) for Android.  I have attached a picture of the error message.

![img_eggsif_2379405409134116756](https://user-images.githubusercontent.com/41639809/57580906-4a3fa400-74b8-11e9-9c92-79b818667cd5.jpg)

**Steps to Reproduce:**
A list of steps that will reproduce the error:
1. Open the app
2. Sometimes it appears straight after launching, other times it appears after clicking on a show, or after opening the settings
3. See error

**Device Information:**
 - Device: P20 Pro
 - OS: EMUI 9
 - CPU Architecture: ARMv8

**Comment by NBTX** [comment]
Closing as this has been addressed in v1.4.5.
Will re-open if it has not actually been resolved.
