### ISSUE TITLE
Change Aspect Ratio - Red Error Screen 

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#25]
This has different steps from the other method mentioned.

Steps to reproduce error:

1. Press play button 3 times, 2-3 seconds between them
2. Press play/pause button again and again
3. Aspect ration change
4. Back to movie page

**Comment by NBTX** [comment]
Please report this issue on the CPlayer repository: https://github.com/ApolloTVofficial/cplayer/issues
