### ISSUE TITLE
[Idea/Request] - TV UI, UX suggestion for episode page & synopsis page

### ISSUE THREAD

**Issue by dscre** [ApolloTVofficial/kamino#253]
https://imgur.com/a/TzQj1pp

_Hi guys! I don't know if TV UI is done. But I've made two images as to how I'd like the movie & series pages would contain info and navigation to the "seasons' page" Please excuse some mistakes._ I very much like the UX to be something like this. Or **maybe incorporate some elements from these images (link above)**. 

**Some explanation:** 
The green dot indicates "watched". 
The grey dot indicates "in progress". 
No dot means not started. 
The 1st button above "S1" is "continue"

I think the seasons bar (vertical bar) in the main page itself would streamline the UX a bit.

_(mistakes in the images: The series' main "page" has wrong format date and rating. Genre is missing. Seasons should be denoted by S01, S02 etc). Also, the grey box containing the series' synopsis could be smaller_

Just my suggestions if the TV UI,UX is still in progress.

**Comment by NBTX** [comment]
We will incorporate your ideas into the TV UI. Thanks!
