### ISSUE TITLE
[Idea/Request/Discussion] Add ApolloTV's app to F-Droid

### ISSUE THREAD

**Issue by JustMeErazem** [ApolloTVofficial/kamino#254]
**What feature would you like added to the app?**
[F-Droid](https://f-droid.org/en/9) is a repository for free and open source Android apps, as well as a store for them (An alternative to the Play Store). I propose ApolloTV's kamino be added to the F-Droid's repo.

**Describe the solution you'd like (optional):**
F-Droid has [some guides](https://f-droid.org/en/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included) on including apps in its repo. The developers of the apps have to be notified and have to confirm they want the app in F-Droid's repo. If kamino doesn't meet F-Droid's inclusion criteria, it can still be included in a [separate repo](https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/).

**Additional context**
F-Droid is great for users, who don't have Google Play Services installed, such as those on custom roms, and including the app in F-Droid can increase it's popularity as well. I can volunteer to help include kamino in F-Droid if wanted/needed.

**Comment by JustMeErazem** [comment]
@NBTX If you agree with including ApolloTV in F-Droid's repo, I'd be more than happy to submit all the metadata myself.

**Comment by NBTX** [comment]
@JustMeErazem It's not possible, F-Droid apps have to be built from source and our app communicates with our server using our secret key that is out of necessity kept exclusively on certain machines (to prevent abuse of the server). Unless we could be one of the edge-cases where they allow us to provide an existing file we can't submit it to F-Droid's repo.

We could, however, run our own repo.

**Comment by JustMeErazem** [comment]
@NBTX Understandable. If you want I can try setting up a Gitlab/Github CI-based repo, something like [rfc2822-firefox](https://gitlab.com/rfc2822/fdroid-firefox), but for now I'll close this issue since it's about adding the app to the main F-Droid repo.
