### ISSUE TITLE
[Request] - DLNA Device Casting

### ISSUE THREAD

**Issue by JLDevUsr** [ApolloTVofficial/kamino#259]
If its even possible I think it would be really nice to be able to cast to DLNA devices (Like Windows Media Player) and other devices.

**Comment by corkiejp** [comment]
See https://github.com/ApolloTVofficial/kamino/issues/255#issuecomment-507212274

For using DLNA casting apps?

**Comment by NBTX** [comment]
Hm yeah, I'm going to consider this a duplicate of #255 - it was opened months earlier but moved from the CPlayer repo as part of my restructuring of the kamino/cplayer repositories.

From now on, #255 should be used to follow the progress of DLNA & Casting, along with controls for these in the app.
