### ISSUE TITLE
TV show navigation in landscape shows error

### ISSUE THREAD

**Issue by blou314** [ApolloTVofficial/kamino#26]
![screenshot_20181126-074918](https://user-images.githubusercontent.com/45358534/49014472-89836e00-f180-11e8-8fed-766e9e47fe63.png)

Navigating through a TV shows season in landscape mode shows error "Bottom overflowed by 10 pixels"

**Comment by NBTX** [comment]
Marking as duplicate of #6 - whilst not directly the same the outcome of a redesign will solve both problems.
