### ISSUE TITLE
Trending and Recently Updated TV Show categories? 

### ISSUE THREAD

**Issue by rushtothesun** [ApolloTVofficial/kamino#267]
The only thing I use Terrarium for anymore is just to look at what's trending and what's been recently aired. Please consider adding these categories.

**Comment by NBTX** [comment]
Okay. We'll look into it.

**Comment by corkiejp** [comment]
> 
> 
> The only thing I use **Terrarium** for anymore is just to look at what's trending and what's been recently aired. Please consider adding these categories.

The app already has a curated list for New Shows, that gets update fairly regularly.
https://www.themoviedb.org/u/ApolloTV/lists

Other than that, get [Seriesguide](https://play.google.com/store/apps/details?id=com.battlelancer.seriesguide) apk to keep a track of air-dates of your favorite shows, will tell you daily what has aired and upcoming in your favorites. trakt.tv support in the app if you use it.

**Comment by rushtothesun** [comment]
> The app already has a curated list for New Shows, that gets updated fairly regularly.
> https://www.themoviedb.org/u/ApolloTV/lists

Yes but that doesn't have shows with new seasons for example.

**Comment by corkiejp** [comment]
Something in the pipeline that may be implemented **soonTM!?**

https://www.themoviedb.org/list/117689

**Comment by NBTX** [comment]
The [Season Premieres list](https://www.themoviedb.org/list/117689) has been added into the app and will be included in the next version.
