### ISSUE TITLE
UI - Single row of pixels appearing below movie name

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#28]
A single row of pixels shows below the name of the movie - as can be seen in the screenshot a purple row of pixels.

This changes colour depending on the image (normally it's the bottom row of pixels from the image)

![image](https://user-images.githubusercontent.com/30179692/49020147-a2435200-f187-11e8-987c-75bd8a1a409b.png)

**Comment by SpajicM** [comment]
Are you sure this is not by design, like a divider?

**Comment by kevincosmos** [comment]
> Are you sure this is not by design, like a divider?

I don't think so, or it would always be the same colour - it looks weird in this example 

![image](https://user-images.githubusercontent.com/30179692/49022410-b3429200-f18c-11e8-826e-0d612641f3ab.png)

**Comment by octoshrimpy** [comment]
It does seem like a bar that didn't get aligned properly. the grey bar is the bottom half of the section that becomes purple when you scroll down.

**Comment by NBTX** [comment]
Fixed (at some point).
