### ISSUE TITLE
'App not installed' on some devices.

### ISSUE THREAD

**Issue by NBTX** [ApolloTVofficial/kamino#3]
Please reply to this issue if this affects you.

**Comment by alfurion** [comment]
Didnt install on either.

Amazon Fire 8 tablet: Fire OS 5.3.6.4 

HTC ONE M8 android 6.0 ; htc sense version 7.0

**Comment by 1aydan** [comment]
Nvidia Shield tablet K1:
32bit ARMv7 quad core cpu

**Comment by smitpat** [comment]
Moto Z Play
ARM A53: https://www.devicespecifications.com/en/model-cpu/be0a3e2a
Android 8.0.0

**Comment by Daplugg23** [comment]
Samsung Galaxy J327a
Android 8.1.0

**Comment by tomforti** [comment]
Sony Bravia XBR-55X700 TV
Android 7.0

**Comment by ospick** [comment]
Samsung SM-T580 (tablet)
7.0

**Comment by kevincosmos** [comment]
> Didnt install on either.
> 
> Amazon Fire 8 tablet: Fire OS 5.3.6.4
> 
> HTC ONE M8 android 6.0 ; htc sense version 7.0



> Nvidia Shield tablet K1:
> 32bit ARMv7 quad core cpu
> Android 7.0 Nougat

Please remember that this beta does not officially support tablets so we won't be assisting with those devices at this time.

**Comment by Dviper18** [comment]
Samsung SM-T580 (tablet)
8.1.0

**Comment by NBTX** [comment]
Solved: We accidentally used the debug APK which is hardcoded for a certain CPU architecture.

**Comment by Noms2** [comment]
Android Oreo
