### ISSUE TITLE
Tags & play button - Same visual style, different uses

### ISSUE THREAD

**Issue by octoshrimpy** [ApolloTVofficial/kamino#31]
When looking at a movie, the tags up top under the movie name have the same styling as the play button. UX-wise, it makes it difficult to know what is clickable and what is not. I assumed I could click on the tags to search for other movies under that tag, since they look like buttons. 

Suggestion: 

Drop the round purple styling on tags, make them purple text instead, separated by dots (how the movie metadata is).

Also remove MOVIE from the movie metadata. if it belongs on the screen at all, it belongs somewhere else. That section has been visually set as "this is extra data about what you're about to watch"

**Comment by kevincosmos** [comment]
Linking this to #29

**Comment by BradB111** [comment]
Partially linked to 4th point in #6 (consistency)

**Comment by NBTX** [comment]
The genres are meant to be clickable. A lot of the app right now consists of placeholders.
Arguably 'MOVIE' is data about what you're going to watch but I think it would be better to put it directly under the title and put the run-time (movie) or number of episodes/average runtime (tv) there.

**Comment by NBTX** [comment]
Both of these points are either in other issues or resolved so I'm closing this issue.
