### ISSUE TITLE
rocket icon in nav too complex

### ISSUE THREAD

**Issue by octoshrimpy** [ApolloTVofficial/kamino#33]
Upon opening the app on my tv, a friend that was hanging at my place quickly asked me why there was a bee with pants in the center nav button. .. I can't say I disagree. Looking at other rocket icons, none of them have that middle horizontal line. [Fontawesome for example](https://fontawesome.com/icons/rocket?style=light). also removing the little "trails" of line under the rocket would help it be much cleaner. 

Suggestion: 
If I am handed an SVG/PNG of the icon, I can create a cleaner SVG version of it, so devs can see what they think.

**Comment by BradB111** [comment]
Rotating this icon to the same angle seen in the app icon may solve this at least for now?

**Comment by NBTX** [comment]
😆 I would actually prefer some form of 'launchpad' icon if at all possible.

[Rocket Icon.zip](https://github.com/ApolloTVofficial/kamino/files/2636057/Rocket.Icon.zip)
Here's the SVG.

**Comment by LilSebastian5000** [comment]
I actually like how it looks lol

**Comment by NBTX** [comment]
Closed as no longer relevant.
(We no longer have this part of the UI.)
