### ISSUE TITLE
Overscroll not in correct place

### ISSUE THREAD

**Issue by octoshrimpy** [ApolloTVofficial/kamino#35]
While in a movie or show page, when pulling on overscroll from the top, the light highlighting that signifies it's got no more content appears under the name, not at the top of the app, against the status bar. 

Suggestion:

Make it purple, and more opaque, and relocate it. I understand if not currently on the roadmap due to beta build. I've seen other apps manage it before, so I know it can be done.

**Comment by dali546** [comment]
Yh I see it... You guys have the ScrollView only to the content and not the SliverAppBar...

But I think that's how it is

**Comment by NBTX** [comment]
Solved by removing top overscroll as it's not really necessary.
