### ISSUE TITLE
Add a 'continue watching' button to a show page

### ISSUE THREAD

**Issue by octoshrimpy** [ApolloTVofficial/kamino#36]
You have to go find the first eposide. Within this first episode, the play button is different than the movies play button. I understand the episode picker section will be refactored, so that's not a big point of this. Instead, I'm referencing a "continue watching" button right on the show's homepage.

**Comment by kevincosmos** [comment]
Continue watching hasn't been implemented yet, closing this issue

**Comment by kevincosmos** [comment]
Closing this and linking to #55
