### ISSUE TITLE
"Pinch" and "Zoom" Gesture Controls

### ISSUE THREAD

**Issue by popycok** [ApolloTVofficial/kamino#40]
The scaling in the app seems to work pretty well except for the search results in landscape mode, They seem pretty oversized where you can only  get the top 1/2 of the The posters on the screen at a time. The season posters are a good size and the main pages look good.

**Comment by kevincosmos** [comment]
Issue still hasn't been addressed - there were conversations about having a "pinch" and "zoom" feature to show more/less on the page - any update on this?

**Comment by NBTX** [comment]
We'll look into this at a later date to discuss the best way to implement this feature.

**Comment by NBTX** [comment]
Fixed.
