### ISSUE TITLE
Long Titles Cut Off

### ISSUE THREAD

**Issue by LilSebastian5000** [ApolloTVofficial/kamino#42]
Hey guys!

Just a stray observation. It appears that shows and movies with long titles get cut off on the screen. Maybe a smaller font or line wrapping in these cases? Galaxy S8+.

![screenshot_20181130-001752](https://user-images.githubusercontent.com/5996311/49269987-abf1e180-f435-11e8-93b1-de4701d17946.jpg)

**Comment by kevincosmos** [comment]
We are aware of this and I think it's already been resolved, I'll leave open until a developer can confirm.
