### ISSUE TITLE
Missing directory (lib/vendor)

### ISSUE THREAD

**Issue by FFY00** [ApolloTVofficial/kamino#43]
**Describe the bug**
The `lib/vendor`directory is missing, preventing us from building the app.

**Comment by NBTX** [comment]
This is intentional, I am working in the documentation to allow you to build your own.

**Comment by kevincosmos** [comment]
Closing as per NBTX's comment, this is intentional.

**Comment by NBTX** [comment]
Actually, I'm going to leave this open to serve as a reminder to make the documentation ASAP.

**Comment by NBTX** [comment]
The documentation is now available in the wiki.
