### ISSUE TITLE
Subtitles!

### ISSUE THREAD

**Issue by paras80** [ApolloTVofficial/kamino#44]
Hey!
I would love if the **subtitles** are added as soon as possible. Since many people has english as their second language it is quite useful and must have. I don't know if it already on to-do list. But Sam told me post it here.
Thankyou...

**Comment by kevincosmos** [comment]
Subtitles are already on the to-do list and are in the pipeline for development, but I cannot confirm an ETA of when they will be implemented. Closing issue since this is already on the to-do list and is now a 'new' suggestion.
