### ISSUE TITLE
Suggestion - App wide search button

### ISSUE THREAD

**Issue by smitpat** [ApolloTVofficial/kamino#47]
**What feature would you like added to the app?**
App wide search button, so even if you click on an episode the search button is always there. It will make it easier to search from anywhere, instead of going back 3,4... times back to page that has a search button. 

**Describe the solution you'd like (optional):**
Solution example: https://imgur.com/bnaeJr1

![apollotv_search](https://user-images.githubusercontent.com/6504120/49838719-0e25dd00-fd7a-11e8-9733-8ed1d209d7ea.png)

**Comment by kevincosmos** [comment]
I believe this has been implemented in the latest beta release. Closing issue.
