### ISSUE TITLE
Allow user to choose how favorites are sorted.

### ISSUE THREAD

**Issue by wondercoolguy** [ApolloTVofficial/kamino#48]
**What feature would you like added to the app?**
Please write a brief description of the feature you would like to help prevent duplicate reports.

So I come from the world of Kodi and it has a really great feature. Once you watch and episode it will be hidden (by choice). If you were watching Ray Donovan and you were completely caught up the show would be hidden until a new episode came out.  If you were watching an old show its a way to know what episode you're on when load the app. To me this is a great feature because it cleans us the interface and lets the user know if there is a new episode.  Other Apps have a feature that hides unaired or "specials" but not watched, this doesn't make sense to me.

Thanks for reading this and doing what you're doing!

**Comment by NBTX** [comment]
I was wondering if we should just collapse the episode or automatically scroll past it rather than hide it altogether - and then we wouldn't have to make it a choice as it's more intuitive.

I don't see the advantage of hiding the show - I mean, couldn't you just not search for it?
May you elaborate further as to what parts of the interface you think the show could or should be hidden from?

**Comment by NBTX** [comment]
Oh of course. Content from your Trakt account would likely be mainly accessed via the 'Continue watching' widget on the homepage which will only show content that has unwatched episodes available.

However, I like the idea of being able to sort favorites according to user preference so I will rename the title of this issue accordingly.

**Comment by wondercoolguy** [comment]
I think the top of the homepage would work those of us who are on Nvidia Shield with no way to use widgets.

**Comment by NBTX** [comment]
No - widgets are our own term (we might have to change it) for cards that you can put on your ApolloTV homepage (the 'launchpad').

**Comment by edmundackah** [comment]
added sorting to favourites
