### ISSUE TITLE
More functional search bar

### ISSUE THREAD

**Issue by octoshrimpy** [ApolloTVofficial/kamino#49]
**What feature would you like added to the app?**
When searching at the moment, the magnifying glass icon stays put on the right side of the bar.
Upon typing, the keyboard has a search button (instead of enter) as expected. However, the magnifying glass stays put, which makes the user have to backspace if they want to change their search. 

**Describe the solution you'd like (optional):**
If you look at Youtube, the search icon turns into an X for quick deletion of search.
The keyboard search button still works, and adding this X would increase functionality. 

**Additional context**

**Comment by NBTX** [comment]
Why is enter expected for the keyboard? The search box is not multiline and the enter/search button performs the search action too.

**Comment by NBTX** [comment]
I guess turning the search icon into an 'x' could work but then I worry people might tap it by accident intending to search - or be confused where the search button is.

Not all people are used to tapping the keyboard shortcut however the ones that are know where to look.

**Comment by octoshrimpy** [comment]
@NBTX within nexus player and a bluetooth keyboard, the enter key does not initiate a search. I have to grab the mouse and manually click on the magnifying glass.

**Comment by edmundackah** [comment]
enter key now causes a new search to occur
