### ISSUE TITLE
Search bar should auto-focus when clicking on the search section

### ISSUE THREAD

**Issue by octoshrimpy** [ApolloTVofficial/kamino#50]
**What feature would you like added to the app?**
When clicking on the bottom bar search section, the search bar should automatically focus. Right now, not counting typing, it takes 4 clicks (including start-search) to get to any movie. 

**Describe the solution you'd like (optional):**
The only functionality in this section is searching, so we can safely assume the user only wants to search. Auto-focusing it removes one of those clicks.

**Comment by kevincosmos** [comment]
Closing as resolved.
