### ISSUE TITLE
single shade of purple not accessibility-friendly

### ISSUE THREAD

**Issue by octoshrimpy** [ApolloTVofficial/kamino#51]
**What feature would you like added to the app?**
Create more expansive app color palette. The purple and the 3 shades of gray look wonderful, but I think we need a lighter version of the purple for text/icons, as it may be hard to read (accessibility, vision problems, old age, etc). 

**Describe the solution you'd like (optional):**
I believe the current color is ##8147ff, which is HSLA(259, 94%, 63%, 1).
I propose adding `purple-light` HSLA(259, 94%, 73%, 1), which is 10% up in lightness, leaving hue and saturation alone, as a color for text and smaller or deselected icons. 
Hex equivalent of `purple-light`: #a279fb.

**Comment by NBTX** [comment]
We've decided to use white/black for headings and main.
Ratings and major controls such as buttons will remain as the existing primary color.
