### ISSUE TITLE
Removal of "results for < ... >" in search page

### ISSUE THREAD

**Issue by octoshrimpy** [ApolloTVofficial/kamino#52]
**What feature would you like added to the app?**
We have the search bar right there, and what we search is what we show results for. Unless we're going to process what the user typed and try to machine-learning-based interpret their misspellings (bad juju, pls don't) then there is no need to show the "Results for " < ... > " text below the search bar.  If nothing comes back from the server, we are displaying a "we've got nothing..." message, and that should be enough to cover all usecases: either we get nothing, or we get stuff. no need to tell the user that we searched for what they typed, immediately below what they typed.

**Comment by edmundackah** [comment]
done
