### ISSUE TITLE
Better progress report on sources search

### ISSUE THREAD

**Issue by SpajicM** [ApolloTVofficial/kamino#57]
Can we have a more detailed progress report on sources search.
Let's say "10/35 sources scraped, 2 found"

That's more reassuring than silently counting down 30 seconds in hope it will find one.

**Comment by NBTX** [comment]
Excellent suggestion. It'll require an adaptation to the server but I very much like this!

**Comment by SamJakob** [comment]
As mentioned by @Dsc on Discord, this should be accompanied by a visual representation.

**Comment by NBTX** [comment]
As mentioned by user Dsc on Discord, this should be accompanied by a visual representation.

**Comment by NBTX** [comment]
Merging with #107
