### ISSUE TITLE
Overhaul Film/TV Genres (TMDb/Trakt List Integration)

### ISSUE THREAD

**Issue by Rowan-Paul** [ApolloTVofficial/kamino#60]
*Suggestion:* have separate categories for the different exclusives (for example Netflix exclusives)

**Comment by edmundackah** [comment]
Find me an API or a website I can scrap from and I will.

**Comment by FlyPigsFly** [comment]
Would these work?

Netflix:
https://en.m.wikipedia.org/wiki/List_of_original_programs_distributed_by_Netflix

Hulu:
https://en.m.wikipedia.org/wiki/List_of_original_programs_distributed_by_Hulu

Amazon:
https://en.m.wikipedia.org/wiki/List_of_original_programs_distributed_by_Amazon

**Comment by FlyPigsFly** [comment]
Yes. Correct me if I'm wrong but that's what we want to build a list of for instance Netflix collections. Titles. Then when a user selects one of these titles do what we always do, go out and scrapes sites for the title selected and watch. The end goal is to show a category of only Netflix titles am I wrong?

**Comment by NBTX** [comment]
Ah I guess if we were going for a 'Netflix only' view that would be pretty helpful.

**Comment by kevincosmos** [comment]
Setting this to 'In Progress' as I have made lists that can be used in Apollo which can be found here:

POPULAR
New HD Releases - https://www.themoviedb.org/list/105604
Animé Shows Top Picks - https://www.themoviedb.org/list/105699
Reddit's Top 250 Films - https://www.themoviedb.org/list/105619
2019 Awards Season (Films) - https://www.themoviedb.org/list/105805
2019 Awards Season (TV Shows) - https://www.themoviedb.org/list/105806

COLLECTIONS
Disney Classic Films - https://www.themoviedb.org/list/105547
DC Comics (Films) - https://www.themoviedb.org/list/105614
DC Extended Universe (Films) - https://www.themoviedb.org/list/105613
Marvel Cinematic Universe (Films) - https://www.themoviedb.org/list/105602
Marvel Cinematic Universe (TV Shows) - https://www.themoviedb.org/list/105804
Marvel Comics (Films) - https://www.themoviedb.org/list/105603

EXCLUSIVES
Netflix Top Picks (Films) - https://www.themoviedb.org/list/105608
Netflix Top Picks (TV Shows) - https://www.themoviedb.org/list/105648
Other Exlusives (Films) - https://www.themoviedb.org/list/105611

**Comment by SpajicM** [comment]
This is done with lists by @kevincosmos
