### ISSUE TITLE
"Watch Trailer" Functionality Using TMDb API

### ISSUE THREAD

**Issue by ospick** [ApolloTVofficial/kamino#61]
Add ability to watch trailers

**Comment by edmundackah** [comment]
Will look into this

**Comment by FlyPigsFly** [comment]
We can pull/scrape the trailer straight from TMDB since they already provide a link to a trailer. It would be cool to load the trailer right in cplayer but on FireTV loading the trailer in Silk browser would suffice. The title of this ticket should also reflect what's being suggested.

**Comment by edmundackah** [comment]
Will look into how to implement this

**Comment by kevincosmos** [comment]
@edmundackah any update on this?

**Comment by SpajicM** [comment]
This is done.
