### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ethanmckellar** [ApolloTVofficial/kamino#63]
**What feature would you like added to the app?**
Please write a brief description of the feature you would like to help prevent duplicate reports.
Ex. I would love it if [...] was implemented.
Ability to delete all text in search field instead of manually deleting all letters
**Describe the solution you'd like (optional):**
If you have any ideas as to how this could be implemented, where appropriate, please specify the steps you'd like us to take.
Ex. I would prefer it if you implemented this feature by doing [...].
In the search field, have an x to delete the current search
**Additional context**

**Comment by SpajicM** [comment]
Done for the next update.

**Comment by kevincosmos** [comment]
Closing as this has been implemented.
