### ISSUE TITLE
(Pending framework update) Trying to change search - keyboard doesn't appear

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#64]
**Describe the bug**
User searches for film (i.e. Toy Story)
User selects Toy Story 2
User selects back and changes mind and wants to watch Django Unchained

**Expected behavior:**
Once the user selects back and tries to change the search, they should be able to type Django Unchained

**Actual behavior:**
Once the user selects back and tries to change the search, they are unable to search as the on-screen keyboard does not appear and the search bar goes grey 

**Steps to Reproduce:**
A list of steps that will reproduce the error.
1. Search for Toy Story
2. Select Toy Story
3. Hit back button
4. Try to change search query

**Screenshots:**

![screenshot_20190106-103151](https://user-images.githubusercontent.com/30179692/50734976-38af5e00-119f-11e9-8b00-0a8e1398ebf9.png) 

**Device Information:**
 - Device: Pixel 2 XL
 - OS: Android 9

**Comment by edmundackah** [comment]
This is an issue with the flutter framework, already opened an issue on the official flutter repository.

**Comment by NBTX** [comment]
Reopening to track https://github.com/flutter/flutter/issues/23862.

**Comment by SpajicM** [comment]
Possible fix/workaround: https://github.com/flutter/flutter/pull/27365

**Comment by kevincosmos** [comment]
The tracked issue (23862) has been resolved

**Comment by SpajicM** [comment]
Can confirm this is fixed when built with Flutter master branch/channel.
I don't suggest releasing a master-based build but I guess dev & beta are stable enough?

Track this to see when next dev branch release rolls out.
https://github.com/flutter/flutter/releases 

Stable branch I don't think it's coming for another couple of months.

**Comment by NBTX** [comment]
@SpajicM Stable release v1.2.1, 9 hours ago ;)

**Comment by SpajicM** [comment]
@NBTX That's "dev" channel. Stable is still 1.0, and releases every quarter
https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

If you think "dev" branch is stable enough for production (probably is tbh), then build with it.

**Comment by NBTX** [comment]
Flutter framework update (v1.2) released.
