### ISSUE TITLE
Hide Welcome Card Toggle - Does Not Refresh Properly

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#66]
**Describe the bug**
If the user hides the welcome card and tries to un-hide it, they must force close the app and re-open for it to appear (whereas the debug card just needs a refresh of the launchpad)

**Expected behavior:**
Welcome card should appear after refreshing the launchpad

**Actual behavior:**
Welcome card does not appear after refresh, user must force close and restart app to achieve desired result

**Steps to Reproduce:**

1. Hide the welcome card in Settings
2. Refresh (welcome card will be hidden)
3. Un-hide the welcome card in Settings
4. Refresh (welcome card will not display as expected)
5. Force close and restart app (welcome card will now display)

**Comment by edmundackah** [comment]
What version of the app are you running? Unable to re-create this bug.

**Comment by edmundackah** [comment]
This bug has been fixed, the update will roll out soon
