### ISSUE TITLE
Visual cue for https links

### ISSUE THREAD

**Issue by FlyPigsFly** [ApolloTVofficial/kamino#67]
**What feature would you like added to the app?**
Give users a visual cue to denote HTTPS links from HTTP links.

**Describe the solution you'd like (optional):**
A small padlock icon could help a user distinguish if the returned link is HTTPS. This could be placed somewhere in association to the link in question. I don't know how results are returned from CLAWS to KAMINO but I presume it might look something like...

> [padlock] {source, provider, file size}
> {source, provider, file size}
> {source, provider, file size}

[padlock] being the visual cue if link is HTTPS

If no HTTPS links are returned then don't display a padlock.

I know google returns HTTPS links for example
https://video-downloads.googleusercontent.com/

When kamino recives a link from claws,

if link begins with https
  insert padlock
elif
  continue as usual
fi

**Additional context**

**Comment by polishboi** [comment]
I think this would look nice, but what does this knowledge actually give you in practice? I'm familiar with the basic concept of HTTPS traffic being more secure, and encrypted, but since you're not sending or receiving anything private I don't see a point.

**Comment by FlyPigsFly** [comment]
It's a visual cue to let a user know that the content being served is encrypted and not able to be seen by an internet service provider. We can be sure for the most part nobody tampered with the data. Wikipedia uses https by default as well as plenty other sites. HTTPS provides benefits other then just protecting personal information.

**Comment by polishboi** [comment]
@FlyPigsFly understandable, have a nice day

**Comment by NBTX** [comment]
Closing as we do not feel that there is any valid reason to distinguish HTTPS traffic from HTTP traffic in this instance. Additionally HTTPS links do not necessarily guarantee that ISPs cannot intercept, tamper with or view traffic.
