### ISSUE TITLE
Status bar ignored of some/all? devices.

### ISSUE THREAD

**Issue by BradB111** [ApolloTVofficial/kamino#7]
![image](https://user-images.githubusercontent.com/17122433/48986867-acc30480-f111-11e8-84d7-c82d439b5271.png)

Device: Oneplus 6T

Status bar ignored showing the series / movie image behind the status icons
(only an issue on brighter images where the white icons disappear)

**Comment by NBTX** [comment]
Duplicate of https://github.com/ApolloTVofficial/kamino/issues/4

**Comment by BradB111** [comment]
Please note this is not a duplicate of issue #4 as it refers to the status bar and NOT the navigation bar

**Comment by NBTX** [comment]
My bad!
