### ISSUE TITLE
Accent colour can affect the colour of some elements of the ui.

### ISSUE THREAD

**Issue by BradB111** [ApolloTVofficial/kamino#72]
**Describe the bug**
When a lighter accent colour is selected some UI elements go black and become hard to read / don't look right.

**Expected behavior:**
For these elements to only change on the 'theme' or only on buttons where the text may become hard to read.

**Actual behavior:**
Black text & UI elements are shown even in the original theme.

**Steps to Reproduce:**
A list of steps that will reproduce the error.
From default settings:
1. Go to 'settings'
2. Go to 'appearance'
3. Set primary colour to a lighter colour, Lime green for example (#8bc34a)
4. go back to home screen and pull down to refresh to see changes.
5. here you will see throughout the app some text and UI elements are the incorrect colour to match the theme.

**Screenshots:**
![image](https://user-images.githubusercontent.com/17122433/51440827-cf613c00-1cc2-11e9-8afb-3873c0da5253.png)

**Device Information:**
 - Device: OnePlus 6T
 - OS: Android 9.0
 - CPU Architecture: arm64-v8a

**Additional context:**
None.

**Comment by NBTX** [comment]
Was there already an issue with this by the way?

**Comment by BradB111** [comment]
@NBTX I mentioned it in the discord quite a while ago but since it was getting close for public release I posted here for easier tracking with discord becoming busier etc...

**Comment by NBTX** [comment]
@BradB111 yeah I just wasn't sure if someone already filed an issue on here. I may just be remembering this one.
