### ISSUE TITLE
Sync Trending Shows from Trakt

### ISSUE THREAD

**Issue by rutvikbhushan** [ApolloTVofficial/kamino#73]
hi i normally dont do this but please its a humble  can you guys please get a trending tv shows category in the tv shows section, you can get it from the trakt website. here is the link - https://trakt.tv/shows/trending

please trending updates shows regularly and tells us which shows are trending unlike popular or any other category  which doesnt update regularly and trending will help the community discover a lot of new tv shows as it updates on a daily basis thank you hope you consider this . you can implement it from the link i gave.

**Comment by F3ttL0rd** [comment]
Beside the "Trending TV shows" please also consider adding "New HD releases"
This is a common category that is available in lots of other 3rd party apps.
Thanks.

**Comment by NBTX** [comment]
I'll look into it in the future. It's unlikely to be in the next release but should turn up at some point.

**Comment by kevincosmos** [comment]
> Beside the "Trending TV shows" please also consider adding "New HD releases"
> This is a common category that is available in lots of other 3rd party apps.
> Thanks.
The following Trakt list could be integrated to facilitate this:
https://trakt.tv/users/giladg/lists/latest-releases?sort=added,asc

**Comment by kevincosmos** [comment]
Closing this as I've proposed a solution to the issue in #60 and set it to "In Progress"
