### ISSUE TITLE
[Enhancement] CPlayer Gestures (Brightness/Volume/±10sec) + Liquid Landscape

### ISSUE THREAD

**Issue by Gymcap** [ApolloTVofficial/kamino#75]
See [NewPipe](https://github.com/TeamNewPipe/NewPipe/releases) (Github) for a visually appealing implementation of these player gestures.
See also VLC for Android for another, not so beautiful implementation.

_All gestures listed are to be used within CPlayer while viewing content._ 

Expected Implementation:

# Vertical Swipe   
• on Left Side = Brightness Adjustment   
• on Right Side = Volume Adjustment

# Double Tap   
• on Left Side = -10 Seconds   
• on Right Side = +10 Seconds

Extra: "Liquid Landscape"?   
Expected Implementation:

• CPlayer will still flip between Landscape views if system rotation is locked. (specifically excluding portrait views)    
See NewPipe again for an example of this.

**Comment by kevincosmos** [comment]
Closing issue, please re-open in the CPlayer repo: 
https://github.com/ApolloTVofficial/cplayer/issues
