### ISSUE TITLE
Exit App via Back Button (Rather Than Force Close)

### ISSUE THREAD

**Issue by PFKThorin** [ApolloTVofficial/kamino#77]
What feature would you like added to the app?

Please write a brief description of the feature you would like to help prevent duplicate reports.
Ex. I would love it if [...] was implemented.

I would love it if there was a way to exit the application other than force-closing. 

Describe the solution you'd like (optional):
If you have any ideas as to how this could be implemented, where appropriate, please specify the steps you'd like us to take.
Ex. I would prefer it if you implemented this feature by doing [...].

In similar apps, hitting the Back button twice exits the app. 

Additional context

**Comment by Dark-Passenger** [comment]
Um isn't this a bug ? Not a suggestion ...

**Comment by NBTX** [comment]
This was a suggestion. The app was not intended to act that way, however we have noted this suggestion and implemented this feature as of version 1.3.0.
