### ISSUE TITLE
Change Server URL within Settings (Developer Options) For Self-Hosted Servers

### ISSUE THREAD

**Issue by SpajicM** [ApolloTVofficial/kamino#78]
I'd like to have a setting with server URL/Auth (Apollo official by default) which we can easily change in case of hosting our own server (or using someone else's that might appear) without having to rebuild the client app.

**Comment by nthacks** [comment]
+1 on this. We could use the official builds with custom server.

**Comment by BTaskaya** [comment]
+1

**Comment by kevincosmos** [comment]
Assigning to @NBTX for input on this - maybe this could be a Developer option by tapping the build number 10 times or something?

**Comment by NBTX** [comment]
This won't be a developer option - this is going to be a regular option. We may push a build that just adds this to mitigate the high load - especially until we've come up with a proper solution.

**Comment by FlyPigsFly** [comment]
It actually might be wise to push out a build that allows users to enable client mode instead of server mode. If we're talking about mitigating high load on the server, allowing users to enter a custom server address will do little if any considering most don't know how to build their own server in the first place.

**Comment by NBTX** [comment]
We have to actually include the server code in the client build but we've realised that the load on the server is abnormally large, so we want to make sure there aren't any memory leaks or anything before we get everyone to run it on their cell phones.

**Comment by NBTX** [comment]
Okay the server load has now been reduced extremely dramatically.
We will implement this feature for the next build.

**Comment by kevincosmos** [comment]
@NBTX are you referring to having the ability to set your own server URL, or client-side scraping as per previous comment you'd made 18 days ago?

**Comment by NBTX** [comment]
The ability to set your own server URL. We need to make more changes to implement client-side scraping.

**Comment by NBTX** [comment]
This has been implemented.
