### ISSUE TITLE
Metadata on Search Results (File Size/Resolution/5.1Ch etc)

### ISSUE THREAD

**Issue by wasuhz** [ApolloTVofficial/kamino#79]
When using other apps you can list all the hosted files and they will show the file size on each link. This is obviously important for higher quality files and it is how I gauge if a file has mutilchannel audio. I use  real debrid and pick a very large file that includes 5.1 audio.

**Comment by kevincosmos** [comment]
Metadata has already been completed, but I don't think it's yet been implemented. Closing issue as resolved pending update.
