### ISSUE TITLE
Loading Doesnt Keep Screen Awake and Other

### ISSUE THREAD

**Issue by gr3en-chronic** [ApolloTVofficial/kamino#8]
Not sure if this is an issue or lack of feature implication, but while loading a source it doesnt keep the screen awake and allows an android phone to go to sleep/lock screen. Not a huge deal it's just the first video streaming app I've seen allow this. If it's already planned awesome. 

Other issue is after starting any sort of stream if I try to go back to the previous page or back for whatever reason the red error page pops up and locks up the app. The only thing to do is close the app and re-open. Galaxy Note 8

**Comment by NBTX** [comment]
Make sure you're using the latest version.
If you don't have a 'Searching for Sources' dialog, you'll need to re-download the app from the URL posted in the Discord server. (It's the same URL)

**Comment by NBTX** [comment]
Okay it's been properly tested, this is working as expected. You are able to put your phone in standby mode and/or leave the app and it'll carry on scraping in the background.

The red error message is an unrelated issue that has been resolved.
