### ISSUE TITLE
Feature Request - List view for episodes

### ISSUE THREAD

**Issue by BeardDesign1** [ApolloTVofficial/kamino#80]
To me the episode view isn't working that well, it's just tideous to scroll through episodes, especially for tv shows that have lots of em.

So could it be possible for you to add a toggle in the upper right corner to switch between a smaller list view, with just basic info (episode number, title) and the regular view?

**Comment by JLDevUsr** [comment]
It would also be nice to have an optional Grid View.

**Comment by SpajicM** [comment]
Gonna merge with https://github.com/ApolloTVofficial/kamino/issues/27

Season and episode selector is gonna be redone eventually
