### ISSUE TITLE
Feature Request - Plugins/Pack

### ISSUE THREAD

**Issue by 515ivan515** [ApolloTVofficial/kamino#81]
It would be nice if you could add a way for developers to make a pack of sources and be able to use and share the sources.

**Comment by kevincosmos** [comment]
I believe there are plans for this in place, assigning to @NBTX to confirm

**Comment by NBTX** [comment]
We're going to discuss the best way to implement this for our server, the community and the users. We may build upon this idea too.

I'm going to respond later when we have a concrete idea about this.

**Comment by NBTX** [comment]
The best way to do this would be to setup and run a server and give out the IP address.
With the new build, people will be able to enter secondary servers into the app and receive additional content.

I will keep revisiting this feature request as we continue to develop this concept.

**Comment by NBTX** [comment]
Closing as for now there are no sources that we plan to exclude from Claws so a pack would be redundant.
