### ISSUE TITLE
Links Found During Scraping

### ISSUE THREAD

**Issue by TittyMcTwister** [ApolloTVofficial/kamino#83]
When scraping for sources it should show how many links have been found.

**Comment by kevincosmos** [comment]
Do you mean during scraping? We either show you the results or tell you none have been found.

**Comment by BradB111** [comment]
I believe this is to show the number of sources as they are found during scraping. (Updated real time)

So dialogue would read:

"Searching for sources: <X> Found "

Maybe this can be expanded to the following when RD is implemented.

"Searching for sources: <X> RD | <Y> Normal"

Or similar?

**Comment by FlyPigsFly** [comment]
Related? https://github.com/ApolloTVofficial/kamino/issues/57

**Comment by TittyMcTwister** [comment]
Ahh sorry didnt see #57 
But meant the same thing

**Comment by kevincosmos** [comment]
Duplicate of 57. Closing.
