### ISSUE TITLE
Cards not working correctly

### ISSUE THREAD

**Issue by Rowan-Paul** [ApolloTVofficial/kamino#84]
If I remove the "welcome to ApolloTV" card it seems to just clone the first card twice. But upon further inspection (by switching the two cards) only the card title moves around even with the welcome card.

Edit: seems a restart of the app fixes it, though not a refresh of the homepage

**Comment by kevincosmos** [comment]
I have reproduced this in a video here:

https://cdn.discordapp.com/attachments/494206606939258896/539364722185601044/2019_01_28_08_40_58.mp4

**Comment by kevincosmos** [comment]
This appears to be resolved in 1.3.2. Closing issue.
