### ISSUE TITLE
List of Feature Requests (Answered)

### ISSUE THREAD

**Issue by AhmedSisy** [ApolloTVofficial/kamino#85]
First of all i would like to thank the devs for their hard work.
Necessary features
1 - External Player support
2 - The ability to load subtitles
3 - Diffrent languages for the app's UI
4 - a log of previous movies and shows watched
5 - Android TV - Firestick remote support 
6 - Chromecast Ability
7 - Realdebird Support
8 - Can you make the UI smoother? 60Fps! Please
9 - Trailer icon on the movie/tv posters
10 - advanced meta data on sources
11 - Cached torrent streaming
And that sums it all up
If the devs can actually do all this it will be hands down the best streaming app

Suggestion - Remove the slide menu completely and put the settings icon at the original place of the slide menu and put the Movies and tv switcher on a single button next to the favorites icon and the button changes to tv icon when you're on the movies page and vice versa

**Comment by kevincosmos** [comment]
Hi, I'm not a dev but thought I'd comment on your suggestions:
1 - External Player support - already planned
2 - The ability to load subtitles - already planned
3 - Diffrent languages for the app's UI - being worked on currently
4 - a log of previous movies and shows watched - already planned
5 - Android TV - Firestick remote support - already planned as a priority
6 - Chromecast Ability - already in development
7 - Realdebird Support - in development
8 - Can you make the UI smoother? 60Fps! Please
9 - Trailer icon on the movie/tv posters - been suggested already, devs will look into this
10 - advanced meta data on sources - we have some metadata stuff ready but not yet implemented I believe
11 - Cached torrent streaming - ongoing discussions around this

**Comment by kevincosmos** [comment]
Answered.
