### ISSUE TITLE
QOL Suggestions - Launchpad

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#89]
- "Favourite TV Shows" and "Favourite Movies" cards should be added to the launchpad

- Ability to go to a page (i.e. TV Shows > Drama/Anime) and then add that list to a card on the launchpad

- Ability to enter Trakt URL for a playlist and sync that into a card (i.e. Disney Classics from https://trakt.tv/users/draackje/lists/disney-animated-classics)

- "[DEVELOPERS] Debug Card" should be removed (maybe revealed if tapping build number 10 times)

**Comment by NBTX** [comment]
We have removed the debug card.
I like the idea of having Trakt playlists. I think we will need to revisit Launchpad widgets.

**Comment by NBTX** [comment]
Launchpad has been completely redesigned from the ground up.

Will definitely consider the Trakt URL card feature as with the ability to go to a page.
Wondering if I should implement some kind of Launchpad widget creator?

**Comment by SpajicM** [comment]
Launchpad widget creator? Over-engginering :D

Trakt as a playlist card seems to be the only point left here.

**Comment by NBTX** [comment]
@SpajicM no like 'enter URL' or 'select category' -> 'add to homepage'

**Comment by kevincosmos** [comment]
Closing this to open individual issues for easier tracking.
