### ISSUE TITLE
App loading Spash Screen aspect ratio

### ISSUE THREAD

**Issue by BradB111** [ApolloTVofficial/kamino#9]
Loading splash screen may not take into account devices with aspect ratios higher than 16:9/9:16  
(Black Space)

![image](https://user-images.githubusercontent.com/17122433/48986817-4211c900-f111-11e8-9c63-433f6d77d1b8.png)

**Comment by kevincosmos** [comment]
This issue also occurs on tablets.

**Comment by NBTX** [comment]
I believe I've solved this but need further testing with the new beta to make sure.

**Comment by BradB111** [comment]
Will let you know asap

**Comment by BradB111** [comment]
fixed for me in latest pre-release

**Comment by NBTX** [comment]
Fixed.
