### ISSUE TITLE
QOL Suggestions - Favorites

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#90]
- Spelling inconsistency. "Favorites" displayed on the tab, but when adding a new one it says "add to favourites".

- Can't add to favorites from launchpad, need to go into "See All" first

- Inside "Favorites" I should be able to hold on an item to then remove it from favorites

- TV and Movie icons seem redundant when inside "Favorites" since they're categorized already.

- It is not clear how the favorites are sorted (last played/alphabetical?) as no sort menu appears when pressing the icon.

**Comment by kevincosmos** [comment]
Reopening issue as only one of these points have been addressed, the following are still valid:

* Can't add to favorites from launchpad, need to go into "See All" first
* Inside "Favorites" I should be able to hold on an item to then remove it from favorites
* TV and Movie icons seem redundant when inside "Favorites" since they're categorized already.
* It is not clear how the favorites are sorted (last played/alphabetical?) as no sort menu appears when pressing the icon.

Can these be addressed/updated? If they're not going to be resolved, issue can be closed again.

**Comment by NBTX** [comment]
> - Can't add to favorites from launchpad, need to go into "See All" first

New launchpad but will take this into consideration with the new design.

<hr>

> - Inside "Favorites" I should be able to hold on an item to then remove it from favorites.

Agreed and noted.

<hr>

> - TV and Movie icons seem redundant when inside "Favorites" since they're categorized already.

Resolved with new favorites layout.
<hr>

> - It is not clear how the favorites are sorted (last played/alphabetical?) as no sort menu appears when pressing the icon.

Will implement a sort menu for favorites.

**Comment by kevincosmos** [comment]
Closing this to open individual issues for easier tracking.
