### ISSUE TITLE
[Suggestion] Automatic downloads

### ISSUE THREAD

**Issue by Rowan-Paul** [ApolloTVofficial/kamino#97]
Don't know if this is possible, but if a new episode comes available from a certain series automatically download it to my SD card.

(Obviously this would be implement later once downloads have been added)

**Comment by SpajicM** [comment]
Downloading won't be implemented AFAIK.

**Comment by kevincosmos** [comment]
There are no plans to implement downloads in ApolloTV. Closing issue.
