### ISSUE TITLE
[Suggestion] Source Ranking

### ISSUE THREAD

**Issue by dali546** [ApolloTVofficial/kamino#98]
This is quite a subtle request and very far off into the future
But using TV Zion I noticed HEVC (H.265) links end up much lower in the lists because of file size even though they may be higher quality

So when we do quality ranking priority by quality rating not file size
Because a 1080p H.265 TV episode is 70MB but a 720p H.264 episode is 270MB

**Comment by kevincosmos** [comment]
Closing as this will be covered in #102
