### ISSUE TITLE
New beta version missing sources

### ISSUE THREAD

**Issue by NeoAtrum** [ApolloTVofficial/kamino#99]
I have the original public beta release running on my phone and one of my Amazon fires and they are able to find sources for the TV shows I watch, but the new beta release on my other fire says "no sources found" on multiple episodes that work on the original release. I have 'manually select sources' enabled on all devices.

**Comment by NBTX** [comment]
It's possible you're being rate limited. Can you try again later but just with the new version - or using the new version first?

**Comment by kevincosmos** [comment]
@NeoAtrum - can you provide an update on the above response please? Otherwise issue will be closed.

**Comment by kevincosmos** [comment]
Closing issue as no response from OP and this hasn't been reported by anybody else.
